const ADD_TODO = 'ADD_TODO';
const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SET_INITIAL_STATE = 'SET_INITIAL_STATE';

export { ADD_TODO, DELETE_ALL_TODOS, COMPLETE_TODO, DELETE_TODO, SET_INITIAL_STATE };
